Correct example commands and output in README to reflect actual behavior of tool
arduino/serial-monitor pull request #16
Opened 2022-05-18 06:11 UTC by per1234

The readme content seems to be based on [the "dummy-monitor" tool](https://github.com/arduino/pluggable-monitor-protocol-handler/tree/main/dummy-monitor) rather than on serial-monitor, and also outdated.

I have updated the commands and output to reflect the behavior of the tool from this repository.

The exception are some differences that are caused by bugs in the `github.com/arduino/pluggable-monitor-protocol-handler` tool:

- Incorrect `values` key names in DESCRIBE command response (https://github.com/arduino/pluggable-monitor-protocol-handler/issues/14)
- Missing QUIT command response (https://github.com/arduino/pluggable-monitor-protocol-handler/issues/13)

The current readme content is written in expectation of specification compliance rather than reflecting the current buggy behavior.

2022-05-18 06:54 UTC, per1234 commented
I think we should wait on a decision on https://github.com/arduino/pluggable-monitor-protocol-handler/issues/14 before merging this. It might be that the specification will be judged incorrect rather than the module behavior. The current readme is 50/50 on use of `values` vs `value` as the key name, so it will need to be updated either way to be made correct.

2022-05-18 07:35 UTC, umbynos requested changes

2022-05-18 07:35 UTC, umbynos commented on README.md
> +        "values": [
```suggestion
        "value": [
```

2022-05-18 07:35 UTC, umbynos commented on README.md
> +        "values": [
```suggestion
        "value": [
```

2022-05-18 07:35 UTC, umbynos commented on README.md
> +        "values": [
```suggestion
        "value": [
```

2022-05-18 07:35 UTC, umbynos commented on README.md
> +        "values": [
```suggestion
        "value": [
```

2022-05-18 07:35 UTC, umbynos commented on README.md
> +        "values": [
```suggestion
        "value": [
```

2022-05-18 08:33 UTC, per1234 commented on README.md
> -CONFIGURE speed 19200
It was removed accidentally. Thanks for catching that. I have fixed it in https://github.com/arduino/serial-monitor/compare/38f313d355a3e07e96c040e046fb4b2fcca73921..ee92d5cf152311efa6047debf5d328b803210009

2022-05-25 07:42 UTC, per1234 commented on README.md
> +        "values": [
The decision was made to adjust the pluggable monitor specification to match the established behavior of `github.com/arduino/pluggable-monitor-protocol-handler` and the tools such as serial-monitor based on it.

So I have made the suggested changes to use the `value` key name as you suggested.

Please take another look when you get a chance @umbynos

2022-05-25 12:54 UTC, merged