Added "rts" and "cts" configuration parameters.
arduino/serial-monitor pull request #21
Opened 2022-08-11 12:21 UTC by cmaglie

This PR adds the `rts` and `cts` configuration parameter that allows to set and reset RTS and CTS lines.

2022-09-01 02:51 UTC, per1234 requested changes

2022-09-01 02:51 UTC, per1234 commented on go.mod
> +go 1.18
I think this outdated part of the readme should also be updated to say the specific version the project is intended to be built with:

https://github.com/arduino/serial-monitor/blob/4d9899604a779c2a6c5184d439a51f0912c4041e/README.md?plain=1#L7

2022-09-01 20:56 UTC, per1234 requested changes
UPDATE: fixed!

<s>

The port is always configured as `dtr=on,rts=off` after the change made in https://github.com/arduino/serial-monitor/pull/21/commits/37305bb2a8f19e6907df9d268aefa1021260727a

For example, any of the following commands:

```text
$ arduino-cli monitor -p COM43 --config dtr=off,rts=off
```

```text
$ arduino-cli monitor -p COM43 --config dtr=on,rts=on
```

```text
$ arduino-cli monitor -p COM43 --config dtr=off,rts=on
```

Produce these states:

![image](https://user-images.githubusercontent.com/8572152/188011153-00e755c8-9d4a-40d7-bd77-b061189548c6.png)

I only checked on Windows. Everything works as expected for me with the version from https://github.com/arduino/serial-monitor/pull/21/commits/4d9899604a779c2a6c5184d439a51f0912c4041e

</s>

2022-09-02 15:45 UTC, cmaglie commented
Thanks for testing it @per1234, I messed up with the control bits, now I pushed a new tentative fix in 8e68f5e

2022-09-03 04:54 UTC, per1234 approved these changes
Everything is working as expected on Windows and Linux with the build from https://github.com/arduino/serial-monitor/pull/21/commits/16a3ef63975391a16d796c08eba8d15fdf9a5158

2022-09-08 15:38 UTC, merged